version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: qp_database
      DB_PORT: 5432
      DB_DIALECT: postgres
      NODE_ENV: development
      MAX_POOL_SIZE: 80
      MIN_POOL_SIZE: 0
      POOL_IDLE: 30000
      POOL_ACQUIRE: 30000
      JWT_SECRET: 8KCwClVAsnjccVgb0mgC9ihaPHGwLCQt
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qp_database